default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: development

# test:
#   <<: *default
#   database: test
#   min_messages: warning
#
# acceptance:
#   <<: *default
#   database: acceptance
#   url: <%= ENV['DATABASE_URL'] %>
#
# production:
#   <<: *default
#   database: production
#   url: <%= ENV['DATABASE_URL'] %>
